import telebot
from telebot import types

bot = telebot.TeleBot('')

@bot.message_handler(commands = ["start"])
def start(message):
    markup = types.InlineKeyboardMarkup(row_width = 2)
    item1 = types.InlineKeyboardButton(text = "Кейсы", callback_data = "case")
    item2 = types.InlineKeyboardButton(text = "Ценник", callback_data = "price")
    markup.add(item1,item2)
    bot.send_message(message.chat.id, "Главное меню", reply_markup = markup)

@bot.callback_query_handler(func=lambda call:True)
def callback_inline(call):
	if call.data == "price":
		bot.answer_callback_query(call.id, text = "1 REELS - 700₽", show_alert = True)
	elif call.data == "case":
		markup = types.InlineKeyboardMarkup()
		item1 = types.InlineKeyboardButton(text = "Махач Гаджиев (ВИДЕОГРАФ)", callback_data = "case1")
		item2 = types.InlineKeyboardButton(text = "Абубакар Сакаев (ПРОДЮСЕР)", callback_data = "case2")
		item3 = types.InlineKeyboardButton(text = "Ибрагим Хайров (ТРЕНЕР ПО РЕЧИ)", callback_data = "case3")
		item4 = types.InlineKeyboardButton(text = "Касик (NFT)", callback_data = "case4")
		item5 = types.InlineKeyboardButton(text = "Курбайтаев (NFT\\INVESTOR)", callback_data = "case5")
		item6 = types.InlineKeyboardButton(text = "Адам (ПСИХОЛОГ)", callback_data = "case6")
		back = types.InlineKeyboardButton(text = "Назад", callback_data = "back")
		markup.add(item1)
		markup.add(item2)
		markup.add(item3)
		markup.add(item4)
		markup.add(item5)
		markup.add(item6)
		markup.add(back)
		bot.edit_message_text(chat_id = call.message.chat.id, message_id = call.message.message_id, text = "Кейсы", reply_markup = markup)
	elif call.data == "back":
		markup = types.InlineKeyboardMarkup(row_width = 2)
		item1 = types.InlineKeyboardButton(text = "Кейсы", callback_data = "case")
		item2 = types.InlineKeyboardButton(text = "Ценник", callback_data = "price")
		markup.add(item1,item2)
		bot.edit_message_text(chat_id = call.message.chat.id, message_id = call.message.message_id, text = "Главное меню", reply_markup=markup)

	elif call.data == "case1":
		markup = types.InlineKeyboardMarkup()
		item1 = types.InlineKeyboardButton(text = "Кейс № 1️⃣  ", url = "https://www.instagram.com/reel/Cd1MBT1JJUU/?igshid=YmMyMTA2M2Y=")
		item2 = types.InlineKeyboardButton(text = "Кейс № 2️⃣  ", url = "https://www.instagram.com/reel/CZr6WaoqVag/?igshid=YmMyMTA2M2Y=")
		item3 = types.InlineKeyboardButton(text = "Кейс № 3️⃣  ", url = "https://www.instagram.com/reel/CZmfLcQKGoJ/?igshid=YmMyMTA2M2Y=")
		item4 = types.InlineKeyboardButton(text = "Кейс № 4️⃣  ", url = "https://www.instagram.com/reel/CX_TNG5D_a8/?igshid=YmMyMTA2M2Y=")
		item5 = types.InlineKeyboardButton(text = "Кейс № 5️⃣  ", url = "https://www.instagram.com/reel/CXg3YOVKMxr/?igshid=YmMyMTA2M2Y=")
		back = types.InlineKeyboardButton(text = "Назад", callback_data = "back1")	
		markup.add(item1)
		markup.add(item2)
		markup.add(item3)
		markup.add(item4)
		markup.add(item5)
		markup.add(back)
		bot.edit_message_text(chat_id = call.message.chat.id, message_id = call.message.message_id, text = "Махач Гаджиев (ВИДЕОГРАФ) Монтировал для него уроки для курса, REELS , а также видео для Youtube", reply_markup = markup)

	elif call.data == "case2":
		markup = types.InlineKeyboardMarkup()
		item1 = types.InlineKeyboardButton(text = "Кейс № 1️⃣  ", url = "https://www.instagram.com/reel/Ce06OH8AOxa/?igshid=YmMyMTA2M2Y=")
		item4 = types.InlineKeyboardButton(text = "Кейс № 4️⃣  ", url = "https://www.instagram.com/reel/CejPwcTlvMi/?igshid=YmMyMTA2M2Y=")
		item2 = types.InlineKeyboardButton(text = "Кейс № 2️⃣  ", url = "https://www.instagram.com/reel/CeLiJdKABin/?igshid=YmMyMTA2M2Y=")
		item5 = types.InlineKeyboardButton(text = "Кейс № 5️⃣  ", url = "https://www.instagram.com/reel/Ced7v_gAn84/?igshid=YmMyMTA2M2Y=")
		item3 = types.InlineKeyboardButton(text = "Кейс № 3️⃣  ", url = "https://www.instagram.com/reel/CeoBNV7gnxl/?igshid=YmMyMTA2M2Y=")
		back = types.InlineKeyboardButton(text = "Назад", callback_data = "back1")	
		markup.add(item1)
		markup.add(item2)
		markup.add(item3)
		markup.add(item4)
		markup.add(item5)
		markup.add(back)
		bot.edit_message_text(chat_id = call.message.chat.id, message_id = call.message.message_id, text = "Абубакар Сакаев (ПРОДЮСЕР)", reply_markup = markup)

	elif call.data == "case3":
		markup = types.InlineKeyboardMarkup()
		item1 = types.InlineKeyboardButton(text = "Кейс № 1️⃣  ", url = "https://www.instagram.com/reel/Cah7f2qKboY/?igshid=YmMyMTA2M2Y=")
		item2 = types.InlineKeyboardButton(text = "Кейс № 2️⃣  ", url = "https://www.instagram.com/reel/CYeLcXxlHwh/?igshid=YmMyMTA2M2Y=")
		item3 = types.InlineKeyboardButton(text = "Кейс № 3️⃣  ", url = "https://www.instagram.com/reel/CakQALuKX3h/?igshid=YmMyMTA2M2Y=")
		item4 = types.InlineKeyboardButton(text = "Кейс № 4️⃣  ", url = "https://www.instagram.com/reel/Ca7WrsqqPYA/?igshid=YmMyMTA2M2Y=")
		item5 = types.InlineKeyboardButton(text = "Кейс № 5️⃣  ", url = "https://www.instagram.com/reel/Ca5JX3Oqfw-/?igshid=YmMyMTA2M2Y=")
		back = types.InlineKeyboardButton(text = "Назад", callback_data = "back1")	
		markup.add(item1)
		markup.add(item2)
		markup.add(item3)
		markup.add(item4)
		markup.add(item5)
		markup.add(back)
		bot.edit_message_text(chat_id = call.message.chat.id, message_id = call.message.message_id, text = "Ибрагим Хайров (ТРЕНЕР ПО РЕЧИ)", reply_markup = markup)

	elif call.data == "case4":
		markup = types.InlineKeyboardMarkup()
		item1 = types.InlineKeyboardButton( text = "Кейс № 1️⃣  ", url = "https://www.instagram.com/reel/CdtBl5mjrPI/?igshid=YmMyMTA2M2Y=")
		item2 = types.InlineKeyboardButton(text = "Кейс № 2️⃣  ", url = "https://www.instagram.com/reel/CeBmY8rDCd-/?igshid=YmMyMTA2M2Y=")
		item3 = types.InlineKeyboardButton(text = "Кейс № 3️⃣  ", url = "https://www.instagram.com/reel/CfEGkBljv9G/?igshid=YmMyMTA2M2Y=")
		back = types.InlineKeyboardButton(text = "Назад", callback_data = "back1")	
		markup.add(item1)
		markup.add(item2)
		markup.add(item3)
		markup.add(back)
		bot.edit_message_text(chat_id = call.message.chat.id, message_id = call.message.message_id, text = "Касик (NFT)",reply_markup=markup)
		
	elif call.data == "case5":
		markup = types.InlineKeyboardMarkup()
		item1 = types.InlineKeyboardButton(text = "Кейс № 1️⃣  ", url = "https://www.instagram.com/reel/Cd6SR8EqvkC/?igshid=YmMyMTA2M2Y=")
		item2 = types.InlineKeyboardButton(text = "Кейс № 2️⃣  ", url = "https://www.instagram.com/reel/CeGjA1cKvFe/?igshid=YmMyMTA2M2Y=")
		item3 = types.InlineKeyboardButton(text = "Кейс № 3️⃣  ", url = "https://www.instagram.com/reel/CeRZWfhKV-I/?igshid=YmMyMTA2M2Y=")
		item4 = types.InlineKeyboardButton(text = "Кейс № 4️⃣  ", url = "https://www.instagram.com/reel/Ce0thR2qSg5/?igshid=YmMyMTA2M2Y=")
		item5 = types.InlineKeyboardButton(text = "Кейс № 5️⃣  ", url = "https://www.instagram.com/reel/CdtBl5mjrPI/?igshid=YmMyMTA2M2Y=")
		back = types.InlineKeyboardButton(text = "Назад", callback_data = "back1")	
		markup.add(item1)
		markup.add(item2)
		markup.add(item3)
		markup.add(item4)
		markup.add(item5)
		markup.add(back)
		bot.edit_message_text(chat_id = call.message.chat.id, message_id = call.message.message_id, text = "Курбайтаев (NFT\\INVESTOR)",reply_markup=markup)
	elif call.data == "case6":
		markup = types.InlineKeyboardMarkup()
		item1 = types.InlineKeyboardButton(text = "Кейс № 1️⃣  ", url = "https://www.instagram.com/reel/CZzPRT8Abz4/?igshid=YmMyMTA2M2Y=")
		item2 = types.InlineKeyboardButton(text = "Кейс № 2️⃣  ", url = "https://www.instagram.com/reel/CZ9f-CBgQr0/?igshid=YmMyMTA2M2Y=")
		item3 = types.InlineKeyboardButton(text = "Кейс № 3️⃣  ", url = "https://www.instagram.com/reel/CaJ9Z6kAwOP/?igshid=YmMyMTA2M2Y=")
		item4 = types.InlineKeyboardButton(text = "Кейс № 4️⃣  ", url = "https://www.instagram.com/reel/CaM5YokAKwx/?igshid=YmMyMTA2M2Y=")
		item5 = types.InlineKeyboardButton(text = "Кейс № 5️⃣  ", url = "https://www.instagram.com/reel/CaU3m7IA-LP/?igshid=YmMyMTA2M2Y=")
		back = types.InlineKeyboardButton(text = "Назад", callback_data = "back1")	
		markup.add(item1)
		markup.add(item2)
		markup.add(item3)
		markup.add(item4)
		markup.add(item5)
		markup.add(back)
		bot.edit_message_text(chat_id= call.message.chat.id, message_id = call.message.message_id, text = "Адам (ПСИХОЛОГ)", reply_markup = markup)
	elif call.data == "back1":
		markup = types.InlineKeyboardMarkup()
		item1 = types.InlineKeyboardButton(text = "Махач Гаджиев (ВИДЕОГРАФ)", callback_data = "case1")
		item2 = types.InlineKeyboardButton(text = "Абубакар Сакаев (ПРОДЮСЕР)", callback_data = "case2")
		item3 = types.InlineKeyboardButton(text = "Ибрагим Хайров (ТРЕНЕР ПО РЕЧИ)", callback_data = "case3")
		item4 = types.InlineKeyboardButton(text = "Касик (NFT)", callback_data = "case4")
		item5 = types.InlineKeyboardButton(text = "Курбайтаев (NFT\\INVESTOR)", callback_data = "case5")
		item6 = types.InlineKeyboardButton(text = "Адам (ПСИХОЛОГ)", callback_data = "case6")
		back = types.InlineKeyboardButton(text = "Назад", callback_data = "back")
		markup.add(item1)
		markup.add(item2)
		markup.add(item3)
		markup.add(item4)
		markup.add(item5)
		markup.add(item6)
		markup.add(back)
		bot.edit_message_text(chat_id = call.message.chat.id, message_id = call.message.message_id, text = "Кейсы", reply_markup = markup)
bot.polling(none_stop=True)
